#super user permissions needed for using docker
sudo: required 
services:
  - docker

# command used for running the container
before_install: 
  - docker build -t pferrervich/docker-react -f Dockerfile.dev .

# All commands used for runing test suite
script: 
  - docker run -e CI=true pferrervich/docker-react npm run test -- --watchAll=false